from pathlib import PurePosixPath

MAX_DOCUMENT_SIZE = 50 * 1024 * 1024
# Keep indexed relative paths comfortably below PostgreSQL's B-tree entry
# limit, including multibyte UTF-8 path components.
MAX_RELATIVE_PATH_BYTES = 2048
INLINE_INDEX_MAX_BYTES = 256 * 1024
INDEX_EMBEDDING_CHUNK_BATCH_SIZE = 16
HYBRID_SEARCH_MIN_CANDIDATES = 20
HYBRID_SEARCH_CANDIDATE_MULTIPLIER = 4
HYBRID_SEARCH_MAX_CANDIDATES = 200
DOCUMENT_RERANK_DEFAULT_CANDIDATES = 15
# Token-based chunk settings for SentenceSplitter
CHUNK_SIZE_TOKENS = 512
CHUNK_OVERLAP_TOKENS = 50
EXPECTED_EMBEDDING_DIMENSION = 1024
MAX_ERROR_MESSAGE_LENGTH = 1000
MAX_READ_LINES = 200
MAX_READ_CHARACTERS = 20_000
VALID_VISIBILITY_SCOPES = {"project", "session"}

DEFAULT_IGNORED_DIRECTORIES = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "dist",
    "build",
    "target",
    "third_party",
    "vendor",
    ".next",
    ".nuxt",
    ".cache",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    ".tox",
    "coverage",
    ".idea",
    ".vscode",
}
DEFAULT_IGNORED_PATTERNS = {
    "*.pyc",
    "*.pyo",
    "*.log",
    "*.tmp",
    "*.lock",
    "*.min.js",
    "*.min.css",
    "*.min.mjs",
    "*.map",
    "*.sqlite",
    "*.db",
    ".DS_Store",
    "Thumbs.db",
    "*.swp",
    "*.swo",
}
GENERATED_FILE_PATTERNS = {
    "*.generated.*",
    "*.g.cs",
    "*.g.go",
    "*.gen.go",
    "*.designer.cs",
    "*_generated.*",
    "*_gen.*",
}
GENERATED_CONTENT_MARKERS = (
    "@generated",
    "automatically generated",
    "code generated",
    "generated by",
    "do not edit this file",
)
SENSITIVE_FILE_PATTERNS = {
    ".env",
    ".env.*",
    "*.pem",
    "*.key",
    "id_rsa",
    "id_ed25519",
    "credentials.json",
    "secrets.*",
}
ARCHIVE_EXTENSIONS = {
    ".7z",
    ".bz2",
    ".gz",
    ".rar",
    ".tar",
    ".tgz",
    ".xz",
    ".zip",
}
EXECUTABLE_EXTENSIONS = {
    ".app",
    ".bat",
    ".bin",
    ".cmd",
    ".com",
    ".dll",
    ".dmg",
    ".exe",
    ".msi",
    ".scr",
    ".so",
}
IMAGE_EXTENSIONS = {
    ".bmp",
    ".gif",
    ".heic",
    ".jpeg",
    ".jpg",
    ".png",
    ".svg",
    ".tif",
    ".tiff",
    ".webp",
}
VIDEO_EXTENSIONS = {
    ".avi",
    ".m4v",
    ".mkv",
    ".mov",
    ".mp4",
    ".mpeg",
    ".mpg",
    ".webm",
    ".wmv",
}
AUDIO_EXTENSIONS = {
    ".aac",
    ".flac",
    ".m4a",
    ".mp3",
    ".ogg",
    ".opus",
    ".wav",
    ".wma",
}
BINARY_TEXT_EXEMPT_EXTENSIONS = {".docx", ".pdf"}
SPECIAL_FILE_EXTENSIONS = {
    "containerfile": ".dockerfile",
    "dockerfile": ".dockerfile",
}


def document_extension(file_name: str) -> str:
    """Return the indexing extension, including conventional extensionless files."""
    normalized_name = PurePosixPath(file_name).name.lower()
    return SPECIAL_FILE_EXTENSIONS.get(
        normalized_name,
        PurePosixPath(normalized_name).suffix,
    )

# Extensions accepted for upload and indexing.
ACCEPTED_EXTENSIONS = (
    # Documents
    {".pdf", ".docx"}
    # Images (OCR via pytesseract)
    | {".bmp", ".gif", ".heic", ".jpeg", ".jpg", ".png", ".tif", ".tiff", ".webp"}
    # Plain text and markup
    | {".csv", ".htm", ".html", ".ipynb", ".json", ".md", ".rst", ".tex", ".txt", ".xml",
       ".yaml", ".yml"}
    # Source code
    | {".bash", ".c", ".coffee", ".cpp", ".cs", ".css", ".dart", ".ex", ".exs",
       ".go", ".groovy", ".h", ".hpp", ".hs", ".java", ".js", ".jsx", ".kt",
       ".lua", ".m", ".php", ".pl", ".proto", ".py", ".r", ".rb", ".rs", ".scala",
       ".sh", ".sql", ".swift", ".ts", ".tsx", ".vue", ".zsh"}
    # Config / data
    | {".cfg", ".conf", ".dockerfile", ".env", ".ini", ".toml"}
)

# Managed project workspaces are editable text/code/config files. Rich binary
# documents and images remain supported for general document ingestion only.
MANAGED_WORKSPACE_WRITABLE_EXTENSIONS = (
    ACCEPTED_EXTENSIONS - {".pdf", ".docx"} - IMAGE_EXTENSIONS
)
